### ISSUE TITLE
New workspaces not created on Ubuntu 22.04 with gnome 42.9

### ISSUE THREAD

**Issue by MushyShaman** [barnscott/newworkspaceshortcut-barnix.io#13]
Hello, lovely idea for a extension however I can't get it to work on my machine.
It is a practically stock installation of Ubuntu 22.04, running gnome 42.9.

CTRL+SUPER+Left/Right works as expected, moving the current workspace and showing the activities view. Unfortunately neither of the create new workspace functions are working though.

I have tried disabling every other gnome extension to ensure it's not some kind of conflict, I've also tried downloading the version 9 for gnome 42 from extensions.gnome.org, and even manually installing version 0.5 from the last commit in 2022 (as per the instructions in the manual installation section of readme).

I have been logging out and back in after each attempt to force a new gnome session (I'm on Wayland).

And just to be extra sure, I've even checked that my system can detect all the keys of these long combinations being pressed at the same.

Will gladly help you to fix this as I'd love to use it!
Many thanks :)

**Comment by barnscott** [comment]
Gnome 44 extension framework had some breaking changes. And, I am now noticing my CHANGELOG is garbage.

I believe it will work if you select Gnome 44 and Version 6 from extensions page:
https://extensions.gnome.org/extension/4597/new-workspace-shortcut/

In the `metadata.json`, you will see it support "41" and "42". So that should do it.

Let me know if you still have trouble. I don't spend a lot of time supporting older versions, so it possible that the shortcuts were actually bound to different keys on that version though.

Worst case, the extension CHC-E provides the same functionality with the ability to define custom keyboard-shortcuts. It is much more robust. But since I personally just prefer that basic functionality, I continue to support this extension for the newest Gnome versions.
https://extensions.gnome.org/extension/4167/custom-hot-corners-extended/

**Comment by barnscott** [comment]
Let me know if you are still having trouble with this. It is possible that the default key-binding from your distro is conflicting. If so, you can use the new extention-settings-panel to modify the default shortcut binding of this extension. Alternatively, you can use `dconf` to modify the default shortcut that your distro configures. 

Let me know how it goes, otherwise, ill close this issue in the next week or so, but we can revisit if you have concerns in the future.
