### ISSUE TITLE
Alt issue and feature request

### ISSUE THREAD

**Issue by teeffelen** [barnscott/newworkspaceshortcut-barnix.io#3]
Hi, I absolutely love your extension for quickly creating new workspaces on the fly!

I do want to warn you about using `ALT` as a shortcut key, as a lot of apps use `ALT` by default.
An example is the `ALT+Left` and `ALT+Right` which are commonly used by (every) browser to go back/forth in browsing history, this extensions hijacks these shortcuts from such applications.
Maybe consider using a different default key combination for moving the workspace left/right (or leave it blank/up to the user, when a configuration option/menu is added).

Besides that little hick-up, maybe a `Move window to new workspace on the left` as well as the current `Move window to new workspace on the right` could be useful, as having more options never hurts and moving the current window to a new workspace does show an animation (unlike moving the entire workspace to the left).

I hope to see this extension grow, as these features should really already be in Gnome by default :)

**Comment by barnscott** [comment]
Thanks for you feedback, this is really helpful!

I didn't realize the conflict with ALT+Right/Left, so ill reconsider that key-binding. There was an old extension for Gnome 3.38 that used the ALT key the same way with vertical-workspaces, which is why I was using it. But with this feedback, I am considering changing it. Do you have any opinions on what the new key-binding should be? Even if I  dont get around to changing it, I hope to add a Settings panel for the user to change the key binding; so worse case, it will be easy for users to change the shortcut :crossed_fingers: 

Regarding moving windows  to the left... I didn't bother including that feature because  i didn't find it very important. By default, you can already use SUPER+ALT+SHIFT+Left/Right to move the in-focus window to the left/right workspace. And, if you are  on the first-workspace, when you use SUPER+ALT+SHIFT+Left, Gnome will automatically create a new workspace on the left. So in my workflow, I only needed to create new-workspaces on the right. This also explains why I chose to use SUPER+ALT+SHIFT+n for my key-binding.

With that said, if you still think it will help your workflow to have a key-binding to move a window to a new-left-workspace, i can add it to my to-do list, since it wont take much effort.

**Comment by Teeffelen** [comment]
Yeah a settings option would be nice, that way people can just configure their own shortcuts -- and view the default ones if they don't read the README before installing 🤦🏽‍♂️

I have changed quite a lot of gnome's default shortcuts, so I do not really know what's being used by default. If I had to suggest a shortcut I'd say look into using `Super` such as `Super+Alt+Left/Right` or `Super+Ctrl+Left/Right`, depending on default gnome shortcuts of course.

Also you are right, you can create a new workspace to the left, but creating a new one in between current workspaces could save a step, instead of having to:
1) move the current window one workspace to the left (default gnome shortcut)
2) move the current window to a new workspace on the right (with this shortcut extension)

But to be honest, this isn't really a necessary feature -- I'd make the config menu a higher priority.

**Comment by barnscott** [comment]
@Teeffelen Havnt gotten around to the Settings menu, but I just circled back merged the changes for ALT keyboard change. I went with CTL+SUPER for now. Also, a few other keyboard shortcuts are added. Hopefully ill upload to extensions.gnome.org today too.

**Comment by barnscott** [comment]
The latest release has the ability to modify the default shortcut key-bindings, so i do not believe this is an issue anymore. Let me know if you have additional thoughts, and we can revisit.
